In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression,Ridge,Lasso,ElasticNet
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [2]:
df = pd.read_csv("BostonHousing.csv")

In [3]:
df.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [4]:
x = df.iloc[:,:12].values

In [5]:
y = df.iloc[:,12].values

In [6]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [7]:
model1 = LinearRegression()
model2 = Ridge(alpha=1)
model3 = Lasso(alpha=1)
model4 = ElasticNet(alpha=1)

In [8]:
model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model3.fit(x_train,y_train)
model4.fit(x_train,y_train)

ElasticNet(alpha=1)

In [9]:
model1.coef_

array([ 1.07589483e-01,  1.16183468e-02,  9.65640746e-02, -1.38041843e+00,
        7.53576142e+00, -4.18015770e+00,  8.71757381e-02,  1.95646639e-01,
        3.15214246e-02, -1.36189942e-03,  9.97958655e-02, -8.20079769e-03])

In [10]:
model2.coef_

array([ 1.07477089e-01,  1.10432437e-02,  1.10795076e-01, -1.31716345e+00,
        4.20239987e+00, -4.20312604e+00,  9.04356611e-02,  1.49472665e-01,
        3.86664525e-02, -1.05888021e-03,  6.29301358e-02, -8.46531349e-03])

In [11]:
model3.coef_

array([ 0.10309406, -0.00212128,  0.11789364, -0.        ,  0.        ,
       -2.0941371 ,  0.08940732,  0.        , -0.        ,  0.00363307,
        0.        , -0.00870025])

In [12]:
model4.coef_

array([ 0.11415046, -0.00163722,  0.1590883 , -0.        ,  0.        ,
       -1.46059374,  0.08782072,  0.        , -0.        ,  0.00250018,
        0.0942678 , -0.00847612])

In [13]:
yp1 = model1.predict(x_test)
yp2 = model2.predict(x_test)
yp3 = model3.predict(x_test)
yp4 = model4.predict(x_test)

In [18]:
print("Model 1 : ",np.sqrt(mean_squared_error(y_test,yp1)))
print("Model 2 : ",np.sqrt(mean_squared_error(y_test,yp2)))
print("Model 3 : ",np.sqrt(mean_squared_error(y_test,yp3)))
print("Model 4 : ",np.sqrt(mean_squared_error(y_test,yp4)))

Model 1 :  4.178487283822615
Model 2 :  4.155326733591868
Model 3 :  4.518659985556733
Model 4 :  4.650510610105617
